export const banqueComplet = {
  Banque: {
    Banque_id: 101,
    Nom_banque: "BANQUE NATIONALE D’ALGÉRIE « BNA »",
    Siege_social: "8 Boulevard Ernesto Che Guevara Alger",
    Telephone: 21439998,
    Fax: 21439494,
    Logo: null,
    openingTime: 8.3,
    closingTime: 16.3,
    descriptions: [
      "La Banque nationale d'Algérie (BNA) est la première banque commerciale algérienne.",
      "Créée le 13 juin 1966, elle exerce toutes les activités d'une banque de dépôt, elle assure notamment le service financier des groupements professionnels, des entreprises",
      "Elle traite toutes les opérations de banque, de change et de crédit dans le cadre de la législation et de la réglementation des banques. ",
    ],
  },
  Prestations: [
    {
      pres_id: 1,
      pres_nom: "ouverture compte courant",
      pres_type: "gestion et tenue de compte",
      frais: 0,
      bank_id: 101,
    },
    {
      pres_id: 2,
      pres_nom: "frais de tenue de compte courant",
      pres_type: "gestion et tenue de compte",
      frais: 500,
      bank_id: 101,
    },
    {
      pres_id: 3,
      pres_nom: "frais de tenue de compte chèque",
      pres_type: "gestion et tenue de compte",
      frais: 200,
      bank_id: 101,
    },
    {
      pres_id: 4,
      pres_nom: "Frais de tenue de compte sur livret",
      pres_type: "gestion et tenue de compte",
      frais: 0,
      bank_id: 101,
    },
    {
      pres_id: 5,
      pres_nom: "Tenue de compte en devise",
      pres_type: "gestion et tenue de compte",
      frais: 0,
      bank_id: 101,
    },
    {
      pres_id: 6,
      pres_nom: "Fermeture compte courant",
      pres_type: "gestion et tenue de compte",
      frais: 0,
      bank_id: 101,
    },
    {
      pres_id: 7,
      pres_nom: "Fermeture compte chèque",
      pres_type: "gestion et tenue de compte",
      frais: 0,
      bank_id: 101,
    },
    {
      pres_id: 8,
      pres_nom: "Fermeture compte sur livret",
      pres_type: "gestion et tenue de compte",
      frais: 0,
      bank_id: 101,
    },
    {
      pres_id: 9,
      pres_nom: "Fermeture compte devise",
      pres_type: "gestion et tenue de compte",
      frais: -1,
      bank_id: 101,
    },
    {
      pres_id: 10,
      pres_nom: "Versement espèces (Client agence)",
      pres_type: "Opération de paiement",
      frais: 0,
      bank_id: 101,
    },
    {
      pres_id: 11,
      pres_nom: "Versement espèces (Tiers)",
      pres_type: "Opération de paiement",
      frais: 0,
      bank_id: 101,
    },
    {
      pres_id: 12,
      pres_nom: "Versement espèces déplacées (Client autre agence)",
      pres_type: "Opération de paiement",
      frais: 0,
      bank_id: 101,
    },
    {
      pres_id: 13,
      pres_nom: "Virement reçu d'un compte de la même agence",
      pres_type: "Opération de paiement",
      frais: 0,
      bank_id: 101,
    },
    {
      pres_id: 14,
      pres_nom:
        "Virement reçu d'un compte d'une autre agence de la même banque",
      pres_type: "Opération de paiement",
      frais: 0,
      bank_id: 101,
    },
    {
      pres_id: 15,
      pres_nom: "Virement devise reçue de l'étranger",
      pres_type: "Opération de paiement",
      frais: -1,
      bank_id: 101,
    },
    {
      pres_id: 16,
      pres_nom: "Rertait espèces",
      pres_type: "Opération de paiement",
      frais: 10,
      bank_id: 101,
    },
    {
      pres_id: 17,
      pres_nom: "Retrait espèces aux guichets d'une autre agence",
      pres_type: "Opération de paiement",
      frais: 20,
      bank_id: 101,
    },
    {
      pres_id: 18,
      pres_nom: "Émission de chèque de banque",
      pres_type: "Opération de paiement",
      frais: 500,
      bank_id: 101,
    },
    {
      pres_id: 19,
      pres_nom: "Émission Chèque de banque déplacée",
      pres_type: "Opération de paiement",
      frais: 750,
      bank_id: 101,
    },
    {
      pres_id: 20,
      pres_nom: "Annulation de chèque de banque (Client)",
      pres_type: "Opération de paiement",
      frais: 200,
      bank_id: 101,
    },
    {
      pres_id: 21,
      pres_nom: "Virement de compte à compte (même agence)",
      pres_type: "Opération de paiement",
      frais: 0,
      bank_id: 101,
    },
    {
      pres_id: 22,
      pres_nom: "Virement ordonné en faveur client d'une autre agence",
      pres_type: "Opération de paiement",
      frais: 50,
      bank_id: 101,
    },
    {
      pres_id: 23,
      pres_nom: "Émission de la première carte",
      pres_type: "CARTE C.I.B",
      frais: 0,
      bank_id: 101,
    },
    {
      pres_id: 24,
      pres_nom: "Renouvèlement",
      pres_type: "CARTE C.I.B",
      frais: 0,
      bank_id: 101,
    },
    {
      pres_id: 25,
      pres_nom: "Reconfection",
      pres_type: "CARTE C.I.B",
      frais: 350,
      bank_id: 101,
    },
    {
      pres_id: 26,
      pres_nom: "Réédition du code secret",
      pres_type: "CARTE C.I.B",
      frais: 150,
      bank_id: 101,
    },
    {
      pres_id: 27,
      pres_nom: "Commission de retrait sur DAB de la banque",
      pres_type: "CARTE C.I.B",
      frais: -2,
      bank_id: 101,
    },
    {
      pres_id: 28,
      pres_nom: "Commission de retrait sur DAB confrère",
      pres_type: "CARTE C.I.B",
      frais: -2,
      bank_id: 101,
    },
    {
      pres_id: 29,
      pres_nom: "Commission de paiement sur TPE/Client",
      pres_type: "CARTE C.I.B",
      frais: 2,
      bank_id: 101,
    },
    {
      pres_id: 30,
      pres_nom: "Commission de paiement sur TPE/Commerçant",
      pres_type: "CARTE C.I.B",
      frais: 2,
      bank_id: 101,
    },
    {
      pres_id: 31,
      pres_nom: "Octroi",
      pres_type: "Carte internationale",
      frais: -1,
      bank_id: 101,
    },
    {
      pres_id: 32,
      pres_nom: "Mise en opposition",
      pres_type: "Carte internationale",
      frais: 0,
      bank_id: 101,
    },
    {
      pres_id: 33,
      pres_nom: "Reconfection",
      pres_type: "Carte internationale",
      frais: 1000,
      bank_id: 101,
    },
    {
      pres_id: 34,
      pres_nom: "Réédition du code secret",
      pres_type: "Carte internationale",
      frais: 1000,
      bank_id: 101,
    },
    {
      pres_id: 35,
      pres_nom: "Changement de code PIN",
      pres_type: "Carte internationale",
      frais: 1000,
      bank_id: 101,
    },
  ],
};
